//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adika_Style_My_Project.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adika_Style_My_Project.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap fotolia_2304414 {
            get {
                object obj = ResourceManager.GetObject("fotolia_2304414", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FotoliaComp_20442098_DMOG2lKstfxqdOl4gizCzVIy19DTpbSt {
            get {
                object obj = ResourceManager.GetObject("FotoliaComp_20442098_DMOG2lKstfxqdOl4gizCzVIy19DTpbSt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FotoliaComp_20442114_LEuayViei0QyXzWbqhPWtgLv9N5eGCHS {
            get {
                object obj = ResourceManager.GetObject("FotoliaComp_20442114_LEuayViei0QyXzWbqhPWtgLv9N5eGCHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FotoliaComp_27962196_TpHXZTsVqSmd09xyvDjflEiQkNV21yvL {
            get {
                object obj = ResourceManager.GetObject("FotoliaComp_27962196_TpHXZTsVqSmd09xyvDjflEiQkNV21yvL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FotoliaComp_28838557_qODMqqbvnsMOY2ZSpyPrAZ6K2eOKu2Pb {
            get {
                object obj = ResourceManager.GetObject("FotoliaComp_28838557_qODMqqbvnsMOY2ZSpyPrAZ6K2eOKu2Pb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sunset {
            get {
                object obj = ResourceManager.GetObject("Sunset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Water_lilies {
            get {
                object obj = ResourceManager.GetObject("Water lilies", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Water_lilies1 {
            get {
                object obj = ResourceManager.GetObject("Water lilies1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap מגף_כאמל {
            get {
                object obj = ResourceManager.GetObject("מגף כאמל", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap מגף_פוקסיה {
            get {
                object obj = ResourceManager.GetObject("מגף פוקסיה", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap מגף_פוקסיה1 {
            get {
                object obj = ResourceManager.GetObject("מגף פוקסיה1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap עדידס {
            get {
                object obj = ResourceManager.GetObject("עדידס", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap תמונה1 {
            get {
                object obj = ResourceManager.GetObject("תמונה1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
